/*
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
*/

package org.openapijsonschematools.client.paths.fakeuploadfiles.post;

import org.openapijsonschematools.client.requestbody.RequestBodySerializer;
import org.openapijsonschematools.client.requestbody.GenericRequestBody;
import org.openapijsonschematools.client.mediatype.MediaType;
import org.openapijsonschematools.client.paths.fakeuploadfiles.post.requestbody.content.multipartformdata.MultipartformdataSchema;
import org.openapijsonschematools.client.requestbody.SerializedRequestBody;

import java.util.AbstractMap;
import java.util.Map;

public class RequestBody {

    public static class MultipartformdataMediaType extends MediaType<MultipartformdataSchema.MultipartformdataSchema1> {
        public MultipartformdataMediaType() {
            super(MultipartformdataSchema.MultipartformdataSchema1.getInstance());
        }
    }

    public static class RequestBody1 extends RequestBodySerializer<SealedRequestBody> {
        public RequestBody1() {
            super(
                Map.ofEntries(
                    new AbstractMap.SimpleEntry<>("multipart/form-data", new MultipartformdataMediaType())
                ),
                false
            );
        }

        public SerializedRequestBody serialize(SealedRequestBody requestBody) {
            MultipartformdataRequestBody requestBody0 = (MultipartformdataRequestBody) requestBody;
            return serialize(requestBody0.contentType(), requestBody0.body().data());
        }
    }

    public static abstract sealed class SealedRequestBody permits MultipartformdataRequestBody {}
    public static final class MultipartformdataRequestBody extends SealedRequestBody implements GenericRequestBody<MultipartformdataSchema.MultipartformdataSchema1Boxed> {
        private final String contentType;
        private final MultipartformdataSchema.MultipartformdataSchema1Boxed body;
        public MultipartformdataRequestBody(MultipartformdataSchema.MultipartformdataSchema1Boxed body) {
            contentType = "multipart/form-data";
            this.body = body;
        }
        @Override
        public String contentType() {
            return contentType;
        }

        @Override
        public MultipartformdataSchema.MultipartformdataSchema1Boxed body() {
            return body;
        }
    }
}
