# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.request_body_post_allof_with_the_last_empty_schema_request_body.post.operation import ApiForPost


class RequestBodyPostAllofWithTheLastEmptySchemaRequestBody(
    ApiForPost,
):
    pass
