# coding: utf-8

"""
    NetHSM
    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.   # noqa: E501
    The version of the OpenAPI document: v1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from __future__ import annotations
from some_api.shared_imports.schema_imports import *  # pyright: ignore [reportWildcardImportFromLibrary]


from some_api.components.schema import key_item


class KeyListTuple(
    typing.Tuple[
        key_item.KeyItemDict,
        ...
    ]
):

    def __new__(cls, arg: typing.Union[KeyListTupleInput, KeyListTuple], configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None):
        return KeyList.validate(arg, configuration=configuration)
KeyListTupleInput = typing.Union[
    typing.List[
        typing.Union[
            key_item.KeyItemDictInput,
            key_item.KeyItemDict,
        ],
    ],
    typing.Tuple[
        typing.Union[
            key_item.KeyItemDictInput,
            key_item.KeyItemDict,
        ],
        ...
    ]
]


@dataclasses.dataclass(frozen=True)
class KeyList(
    schemas.Schema[schemas.immutabledict, KeyListTuple]
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    types: typing.FrozenSet[typing.Type] = frozenset({tuple})
    items: typing.Type[key_item.KeyItem] = dataclasses.field(default_factory=lambda: key_item.KeyItem) # type: ignore
    type_to_output_cls: typing.Mapping[
        typing.Type,
        typing.Type
    ] = dataclasses.field(
        default_factory=lambda: {
            tuple: KeyListTuple
        }
    )

    @classmethod
    def validate(
        cls,
        arg: typing.Union[
            KeyListTupleInput,
            KeyListTuple,
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> KeyListTuple:
        return super().validate_base(
            arg,
            configuration=configuration,
        )
