# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from petstore_api import api_client, exceptions

from petstore_api.components.schema import object_model_with_ref_props

class RequestBody(api_client.RequestBody):
    content = {
        'application/json': api_client.MediaType(
            schema=object_model_with_ref_props.ObjectModelWithRefProps,
        ),
    }
