package org.openapijsonschematools.components.schemas;
import org.openapijsonschematools.configurations.SchemaConfiguration;
import org.openapijsonschematools.schemas.AnyTypeJsonSchema;
import org.openapijsonschematools.schemas.FrozenList;
import org.openapijsonschematools.schemas.FrozenMap;
import org.openapijsonschematools.schemas.JsonSchema;
import org.openapijsonschematools.schemas.ListJsonSchema;
import org.openapijsonschematools.schemas.MapJsonSchema;
import org.openapijsonschematools.schemas.NotAnyTypeJsonSchema;
import org.openapijsonschematools.schemas.UnsetAnyTypeJsonSchema;

import java.util.AbstractMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.time.LocalDate;
import java.time.ZonedDateTime;
import java.util.UUID;
import org.openapijsonschematools.schemas.StringJsonSchema;

public class Capitalization {
    // nest classes so all schemas and input/output classes can be public
    
    
    public class SmallCamel implements JsonSchema {
        static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            String.class
        ));
        public static String validate(String arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(SmallCamel.class, arg, configuration);
        }
    }    
    
    public class CapitalCamel implements JsonSchema {
        static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            String.class
        ));
        public static String validate(String arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(CapitalCamel.class, arg, configuration);
        }
    }    
    
    public class SmallSnake implements JsonSchema {
        static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            String.class
        ));
        public static String validate(String arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(SmallSnake.class, arg, configuration);
        }
    }    
    
    public class CapitalSnake implements JsonSchema {
        static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            String.class
        ));
        public static String validate(String arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(CapitalSnake.class, arg, configuration);
        }
    }    
    
    public class SCAETHFlowPoints implements JsonSchema {
        static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            String.class
        ));
        public static String validate(String arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(SCAETHFlowPoints.class, arg, configuration);
        }
    }    
    
    public class ATTNAME implements JsonSchema {
        static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            String.class
        ));
        public static String validate(String arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(ATTNAME.class, arg, configuration);
        }
    }    
    
    public class Capitalization1 implements JsonSchema {
        /*
        NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
        Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
    
        Do not edit the class manually.
        */
        static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            FrozenMap.class
        ));
        static final LinkedHashMap<String, Class<?>> properties = new LinkedHashMap<>(Map.ofEntries(
            new AbstractMap.SimpleEntry<String, Class<?>>("smallCamel", SmallCamel.class),
            new AbstractMap.SimpleEntry<String, Class<?>>("CapitalCamel", CapitalCamel.class),
            new AbstractMap.SimpleEntry<String, Class<?>>("small_Snake", SmallSnake.class),
            new AbstractMap.SimpleEntry<String, Class<?>>("Capital_Snake", CapitalSnake.class),
            new AbstractMap.SimpleEntry<String, Class<?>>("SCA_ETH_Flow_Points", SCAETHFlowPoints.class),
            new AbstractMap.SimpleEntry<String, Class<?>>("ATT_NAME", ATTNAME.class)
        ));
        public static <T extends FrozenMap> T validate(Map<String, Object> arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(Capitalization1.class, arg, configuration);
        }
    }
}
