package org.openapijsonschematools.components.schemas;
import java.util.AbstractMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import org.openapijsonschematools.configurations.SchemaConfiguration;
import org.openapijsonschematools.schemas.validation.FrozenMap;
import org.openapijsonschematools.schemas.validation.JsonSchema;

public class HealthCheckResult {
    // nest classes so all schemas and input/output classes can be public
    
    
    public class NullableMessage extends JsonSchema {
        public static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            Void.class,
            String.class
        ));
        public static Void validate(Void arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(NullableMessage.class, arg, configuration);
        }
        public static String validate(String arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(NullableMessage.class, arg, configuration);
        }
    }    
    
    public static class HealthCheckResultMap extends FrozenMap<String, Object> {
        HealthCheckResultMap(FrozenMap<? extends String, ?> m) {
            super(m);
        }
        public static HealthCheckResultMap of(Map<String, Object> arg, SchemaConfiguration configuration) {
            return HealthCheckResult1.validate(arg, configuration);
        }
    }    
    
    public class HealthCheckResult1 extends JsonSchema {
        /*
        NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
        Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
    
        Do not edit the class manually.
    
        Just a string to inform instance is up and running. Make it nullable in hope to get it as pointer in generated model.
        */
        public static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            FrozenMap.class
        ));
        public static final LinkedHashMap<String, Class<?>> properties = new LinkedHashMap<>(Map.ofEntries(
            new AbstractMap.SimpleEntry<String, Class<?>>("NullableMessage", NullableMessage.class)
        ));
        protected static HealthCheckResultMap getMapOutputInstance(FrozenMap<? extends String, ?> arg) {
            return new HealthCheckResultMap(arg);
        }
        public static <T extends FrozenMap> T validate(Map<String, Object> arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(HealthCheckResult1.class, arg, configuration);
        }
    }
}
