package org.openapijsonschematools.components.schemas;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import org.openapijsonschematools.configurations.SchemaConfiguration;
import org.openapijsonschematools.schemas.BooleanJsonSchema;
import org.openapijsonschematools.schemas.DateTimeJsonSchema;
import org.openapijsonschematools.schemas.Int32JsonSchema;
import org.openapijsonschematools.schemas.Int64JsonSchema;
import org.openapijsonschematools.schemas.validation.FrozenMap;
import org.openapijsonschematools.schemas.validation.JsonSchema;
import org.openapijsonschematools.schemas.validation.KeywordEntry;
import org.openapijsonschematools.schemas.validation.KeywordValidator;
import org.openapijsonschematools.schemas.validation.PropertiesValidator;
import org.openapijsonschematools.schemas.validation.PropertyEntry;
import org.openapijsonschematools.schemas.validation.TypeValidator;

public class Order {
    // nest classes so all schemas and input/output classes can be public
    
    
    public class Id extends Int64JsonSchema {}
    
    
    public class PetId extends Int64JsonSchema {}
    
    
    public class Quantity extends Int32JsonSchema {}
    
    
    public class ShipDate extends DateTimeJsonSchema {}
    
    
    public class Status extends JsonSchema {
        public static final LinkedHashMap<String, KeywordValidator> keywordToValidator = new LinkedHashMap<>(Map.ofEntries(
            new KeywordEntry("type", new TypeValidator(Set.of(
                String.class
            )))
        ));
        public static String validate(String arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(Status.class, arg, configuration);
        }
    }    
    
    public class Complete extends BooleanJsonSchema {}
    
    
    public static class OrderMap extends FrozenMap<String, Object> {


        OrderMap(FrozenMap<String, Object> m) {


            super(m);
        }
        public static OrderMap of(Map<String, Object> arg, SchemaConfiguration configuration) {

            return Order1.validate(arg, configuration);
        }
        
        public long:

            val = self.get("id", schemas.unset)
            if isinstance(val, schemas.Unset):
                return val
            return typing.cast(
                long,

                val
            )
        
        public long:

            val = self.get("petId", schemas.unset)
            if isinstance(val, schemas.Unset):
                return val
            return typing.cast(
                long,

                val
            )
        
        public int:

            val = self.get("quantity", schemas.unset)
            if isinstance(val, schemas.Unset):
                return val
            return typing.cast(
                int,

                val
            )
        
        public String:

            val = self.get("shipDate", schemas.unset)
            if isinstance(val, schemas.Unset):
                return val
            return typing.cast(
                String,

                val
            )
        
        public String:

            val = self.get("status", schemas.unset)
            if isinstance(val, schemas.Unset):
                return val
            return typing.cast(
                String,

                val
            )
        
        public boolean:

            val = self.get("complete", schemas.unset)
            if isinstance(val, schemas.Unset):
                return val
            return typing.cast(
                boolean,

                val
            )
        
        public Object getAdditionalProperty(String name) {
            schemas.raise_if_key_known(name, self.__required_keys__, self.__optional_keys__)
            return self.get(name, schemas.unset)
    }    
    
    public class Order1 extends JsonSchema {
        /*
        NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
        Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
    
        Do not edit the class manually.
        */
        public static final LinkedHashMap<String, KeywordValidator> keywordToValidator = new LinkedHashMap<>(Map.ofEntries(
            new KeywordEntry("type", new TypeValidator(Set.of(FrozenMap.class))),
            new KeywordEntry("properties", new PropertiesValidator(Map.ofEntries(
                new PropertyEntry("id", Id.class),
                new PropertyEntry("petId", PetId.class),
                new PropertyEntry("quantity", Quantity.class),
                new PropertyEntry("shipDate", ShipDate.class),
                new PropertyEntry("status", Status.class),
                new PropertyEntry("complete", Complete.class)
            )))
        ));
        protected static OrderMap getMapOutputInstance(FrozenMap<String, Object> arg) {


            return new OrderMap(arg);
        }
        public static OrderMap validate(Map<String, Object> arg, SchemaConfiguration configuration) {

            return JsonSchema.validate(Order1.class, arg, configuration);
        }
    }
}
