package org.openapijsonschematools.components.schemas;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import org.openapijsonschematools.configurations.SchemaConfiguration;
import org.openapijsonschematools.schemas.FrozenMap;
import org.openapijsonschematools.schemas.JsonSchema;
import org.openapijsonschematools.schemas.StringJsonSchema;

public class ReqPropsFromExplicitAddProps {
    // nest classes so all schemas and input/output classes can be public
    
    
    public class AdditionalProperties extends StringJsonSchema {}
    
    
    public static class ReqPropsFromExplicitAddPropsMap extends FrozenMap<String, Object> {
        ReqPropsFromExplicitAddPropsMap(FrozenMap<? extends String, ?> m) {
            super(m);
        }
        public static ReqPropsFromExplicitAddPropsMap of(Map<String, Object> arg, SchemaConfiguration configuration) {
            return ReqPropsFromExplicitAddProps1.validate(arg, configuration);
        }
    }    
    
    public class ReqPropsFromExplicitAddProps1 extends JsonSchema {
        /*
        NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
        Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
    
        Do not edit the class manually.
        */
        public static final LinkedHashSet<Class<?>> type = new LinkedHashSet<>(Set.of(
            FrozenMap.class
        ));
        public static final Set<String> required = new LinkedHashSet<>(Set.of(
            "invalid-name",
            "validName"
        ));
        static final Class<?> additionalProperties = AdditionalProperties.class;
        protected static ReqPropsFromExplicitAddPropsMap getMapOutputInstance(FrozenMap<? extends String, ?> arg) {
            return new ReqPropsFromExplicitAddPropsMap(arg);
        }
        public static <T extends FrozenMap> T validate(Map<String, Object> arg, SchemaConfiguration configuration) {
            return JsonSchema.validate(ReqPropsFromExplicitAddProps1.class, arg, configuration);
        }
    }
}
