# coding: utf-8
"""
    openapi 3.0.3 sample spec
    sample spec for testing openapi functionality, built from json schema tests for draft6  # noqa: E501
    The version of the OpenAPI document: 0.0.1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

import dataclasses
import typing

import urllib3

from unit_test_api import schemas


class ApiResponse:
    def __init__(
        self,
        *,
        response: urllib3.HTTPResponse,
        body: typing.Union[schemas.Unset, schemas.OUTPUT_BASE_TYPES] = schemas.unset,
        headers: typing.Union[schemas.Unset, typing.Mapping[str, schemas.OUTPUT_BASE_TYPES]] = schemas.unset
    ):
        self.response = response
        self.body = body
        self. headers = headers


class ApiResponseWithoutDeserialization(ApiResponse):
    def __init__(
        self,
        *,
        response: urllib3.HTTPResponse,
        body: schemas.Unset = schemas.unset,
        headers: schemas.Unset = schemas.unset
    ):
        self.response = response
        self.body = body
        self. headers = headers
