# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from petstore_api.paths.fake_parameter_collisions1_abab_self_ab.post.operation import ApiForPost


class FakeParameterCollisions1ABAbSelfAB(
    ApiForPost,
):
    pass
