# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.request_body_post_minproperties_validation_request_body.post.operation import PostMinpropertiesValidationRequestBody
from unit_test_api.paths.response_body_post_minproperties_validation_with_a_decimal_response_body_for_content_types.post.operation import PostMinpropertiesValidationWithADecimalResponseBodyForContentTypes
from unit_test_api.paths.response_body_post_minproperties_validation_response_body_for_content_types.post.operation import PostMinpropertiesValidationResponseBodyForContentTypes
from unit_test_api.paths.request_body_post_minproperties_validation_with_a_decimal_request_body.post.operation import PostMinpropertiesValidationWithADecimalRequestBody


class MinPropertiesApi(
    PostMinpropertiesValidationRequestBody,
    PostMinpropertiesValidationWithADecimalResponseBodyForContentTypes,
    PostMinpropertiesValidationResponseBodyForContentTypes,
    PostMinpropertiesValidationWithADecimalRequestBody,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
