# coding: utf-8
"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

import dataclasses
import typing

from petstore_api import server




@dataclasses.dataclass
class Server0(server.Server):
    _url: str = "https://petstore.swagger.io/v2"
