# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from petstore_api.shared_imports.response_imports import *

from . import content


@dataclasses.dataclass
class ApiResponseFor404(api_response.ApiResponse):
    response: urllib3.HTTPResponse
    body: immutabledict.immutabledict[str, schemas.OUTPUT_BASE_TYPES]
    headers: schemas.Unset = schemas.unset


class ResponseFor404(api_client.OpenApiResponse[ApiResponseFor404]):
    response_cls = ApiResponseFor404


    class ApplicationJsonMediaType(api_client.MediaType):
        schema: typing_extensions.TypeAlias = content.application_json.schema.Schema
    Content = typing_extensions.TypedDict(
        'Content',
        {
            'application/json': typing.Type[ApplicationJsonMediaType],
        }
    )
    content: Content = {
        'application/json': ApplicationJsonMediaType,
    }
