# coding: utf-8

"""
    openapi 3.1.0 sample spec
    sample spec for testing openapi functionality, built from json schema tests for draft2020-12  # noqa: E501
    The version of the OpenAPI document: 0.0.1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from __future__ import annotations
from unit_test_api.shared_imports.schema_imports import *  # pyright: ignore [reportWildcardImportFromLibrary]



class ConstWith0DoesNotMatchOtherZeroLikeTypesConst:

    @schemas.classproperty
    def POSITIVE_0(cls) -> typing.Literal["0"]:
        return ConstWith0DoesNotMatchOtherZeroLikeTypes.validate("0")


@dataclasses.dataclass(frozen=True)
class ConstWith0DoesNotMatchOtherZeroLikeTypes(
    schemas.AnyTypeSchema[schemas.immutabledict[str, schemas.OUTPUT_BASE_TYPES], typing.Tuple[schemas.OUTPUT_BASE_TYPES, ...]],
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    # any type
    const_value_to_name: typing.Mapping[typing.Union[int, float, str, schemas.Bool, None], str] = dataclasses.field(
        default_factory=lambda: {
            "0": "POSITIVE_0",
        }
    )
    const = ConstWith0DoesNotMatchOtherZeroLikeTypesConst

