# coding: utf-8

"""
    OpenAPI Petstore
    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose.  # noqa: E501
    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.fake_parameter_collisions1_abab_self_ab.post.operation import ParameterCollisions
from openapi_client.paths.fake_obj_in_query.get.operation import ObjectInQuery
from openapi_client.paths.fake_query_param_with_json_content_type.get.operation import QueryParamWithJsonContentType
from openapi_client.paths.fake_json_form_data.get.operation import JsonFormData
from openapi_client.paths.common_param_sub_dir.delete.operation import DeleteCommonParam
from openapi_client.paths.common_param_sub_dir.get.operation import GetCommonParam
from openapi_client.paths.common_param_sub_dir.post.operation import PostCommonParam
from openapi_client.paths.fake_body_with_file_schema.put.operation import BodyWithFileSchema
from openapi_client.paths.fake_json_patch.patch.operation import JsonPatch
from openapi_client.paths.fake_response_without_schema.get.operation import ResponseWithoutSchema
from openapi_client.paths.fake_pem_content_type.get.operation import PemContentType
from openapi_client.paths.fake_refs_boolean.post.operation import Boolean
from openapi_client.paths.fake_refs_string.post.operation import String
from openapi_client.paths.fake_wild_card_responses.get.operation import WildCardResponses
from openapi_client.paths.fake_refs_mammal.post.operation import Mammal
from openapi_client.paths.fake_upload_download_file.post.operation import UploadDownloadFile
from openapi_client.paths.fake_json_with_charset.post.operation import JsonWithCharset
from openapi_client.paths.fake_upload_files.post.operation import UploadFiles
from openapi_client.paths.fake_inline_composition.post.operation import InlineComposition
from openapi_client.paths.fake_refs_array_of_enums.post.operation import ArrayOfEnums
from openapi_client.paths.fake_multiple_request_body_content_types.post.operation import MultipleRequestBodyContentTypes
from openapi_client.paths.solidus.get.operation import SlashRoute
from openapi_client.paths.fake_health.get.operation import FakeHealthGet
from openapi_client.paths.fake_delete_coffee_id.delete.operation import DeleteCoffee
from openapi_client.paths.fake_case_sensitive_params.put.operation import CaseSensitiveParams
from openapi_client.paths.fake_ref_obj_in_query.get.operation import RefObjectInQuery
from openapi_client.paths.fake_test_query_paramters.put.operation import QueryParameterCollectionFormat
from openapi_client.paths.fake_upload_file.post.operation import UploadFile
from openapi_client.paths.fake_refs_arraymodel.post.operation import ArrayModel
from openapi_client.paths.fake_multiple_securities.get.operation import MultipleSecurities
from openapi_client.paths.fake_refs_object_model_with_ref_props.post.operation import ObjectModelWithRefProps
from openapi_client.paths.fake_refs_number.post.operation import NumberWithValidations
from openapi_client.paths.fake_multiple_response_bodies.get.operation import MultipleResponseBodies
from openapi_client.paths.fake_inline_additional_properties.post.operation import InlineAdditionalProperties
from openapi_client.paths.fake_redirection.get.operation import Redirection
from openapi_client.paths.fake_additional_properties_with_array_of_enums.get.operation import AdditionalPropertiesWithArrayOfEnums
from openapi_client.paths.fake_refs_enum.post.operation import StringEnum
from openapi_client.paths.fake.delete.operation import GroupParameters
from openapi_client.paths.fake.get.operation import EnumParameters
from openapi_client.paths.fake.patch.operation import ClientModel
from openapi_client.paths.fake.post.operation import EndpointParameters
from openapi_client.paths.fake_body_with_query_params.put.operation import BodyWithQueryParams
from openapi_client.paths.fake_refs_composed_one_of_number_with_validations.post.operation import ComposedOneOfDifferentTypes


class FakeApi(
    ParameterCollisions,
    ObjectInQuery,
    QueryParamWithJsonContentType,
    JsonFormData,
    DeleteCommonParam,
    GetCommonParam,
    PostCommonParam,
    BodyWithFileSchema,
    JsonPatch,
    ResponseWithoutSchema,
    PemContentType,
    Boolean,
    String,
    WildCardResponses,
    Mammal,
    UploadDownloadFile,
    JsonWithCharset,
    UploadFiles,
    InlineComposition,
    ArrayOfEnums,
    MultipleRequestBodyContentTypes,
    SlashRoute,
    FakeHealthGet,
    DeleteCoffee,
    CaseSensitiveParams,
    RefObjectInQuery,
    QueryParameterCollectionFormat,
    UploadFile,
    ArrayModel,
    MultipleSecurities,
    ObjectModelWithRefProps,
    NumberWithValidations,
    MultipleResponseBodies,
    InlineAdditionalProperties,
    Redirection,
    AdditionalPropertiesWithArrayOfEnums,
    StringEnum,
    GroupParameters,
    EnumParameters,
    ClientModel,
    EndpointParameters,
    BodyWithQueryParams,
    ComposedOneOfDifferentTypes,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
