# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""


from petstore_api.components.responses import response_success_description_only
_200 = response_success_description_only.SuccessDescriptionOnly
