# coding: utf-8

"""
    openapi 3.0.3 sample spec
    sample spec for testing openapi functionality, built from json schema tests for draft6  # noqa: E501
    The version of the OpenAPI document: 0.0.1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from __future__ import annotations
from unit_test_api.shared_imports.schema_imports import *

AdditionalProperties: typing_extensions.TypeAlias = schemas.BoolSchema


class AdditionalpropertiesCanExistByItselfDict(schemas.immutabledict[str, schemas.OUTPUT_BASE_TYPES]):
    
    def __getitem__(self, name: str) -> bool:
        # dict_instance[name] accessor
        return super().__getitem__(name)

    def __new__(cls, arg: AdditionalpropertiesCanExistByItselfDictInput, configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None):
        return AdditionalpropertiesCanExistByItself.validate(arg, configuration=configuration)
AdditionalpropertiesCanExistByItselfDictInput = typing.Mapping[
    str,
    bool,
]


@dataclasses.dataclass(frozen=True)
class AdditionalpropertiesCanExistByItself(
    schemas.DictSchema[AdditionalpropertiesCanExistByItselfDict]
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    types: typing.FrozenSet[typing.Type] = frozenset({schemas.immutabledict})
    additional_properties: typing.Type[AdditionalProperties] = dataclasses.field(default_factory=lambda: AdditionalProperties) # type: ignore
    type_to_output_cls: typing.Mapping[
        typing.Type,
        typing.Type
    ] = dataclasses.field(
        default_factory=lambda: {
            schemas.immutabledict: AdditionalpropertiesCanExistByItselfDict
        }
    )

    @classmethod
    def validate(
        cls,
        arg: typing.Union[
            AdditionalpropertiesCanExistByItselfDictInput,
            AdditionalpropertiesCanExistByItselfDict,
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> AdditionalpropertiesCanExistByItselfDict:
        return super().validate(
            arg,
            configuration=configuration,
        )

