# coding: utf-8

"""
    openapi 3.0.3 sample spec
    sample spec for testing openapi functionality, built from json schema tests for draft6  # noqa: E501
    The version of the OpenAPI document: 0.0.1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from __future__ import annotations
from unit_test_api.shared_imports.schema_imports import *

AdditionalProperties: typing_extensions.TypeAlias = schemas.BoolSchema
Foo: typing_extensions.TypeAlias = schemas.AnyTypeSchema
Bar: typing_extensions.TypeAlias = schemas.AnyTypeSchema
Properties = typing_extensions.TypedDict(
    'Properties',
    {
        "foo": typing.Type[Foo],
        "bar": typing.Type[Bar],
    }
)


class AdditionalpropertiesAllowsASchemaWhichShouldValidateDict(schemas.immutabledict[str, schemas.OUTPUT_BASE_TYPES]):
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["foo"]) -> schemas.OUTPUT_BASE_TYPES:
        ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bar"]) -> schemas.OUTPUT_BASE_TYPES:
        ...
    
    @typing.overload
    def __getitem__(self, name: str) -> bool:
        ...
    
    def __getitem__(
        self,
        name: typing.Union[
            typing_extensions.Literal["foo"],
            typing_extensions.Literal["bar"],
            str
        ]
    ):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    def __new__(cls, arg: AdditionalpropertiesAllowsASchemaWhichShouldValidateDictInput, configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None):
        return AdditionalpropertiesAllowsASchemaWhichShouldValidate.validate(arg, configuration=configuration)
AdditionalpropertiesAllowsASchemaWhichShouldValidateDictInput = typing.Mapping[
    str,
    typing.Union[
        typing.Union[
            dict,
            schemas.immutabledict,
            str,
            datetime.date,
            datetime.datetime,
            uuid.UUID,
            int,
            float,
            bool,
            None,
            list,
            tuple,
            bytes,
            io.FileIO,
            io.BufferedReader
        ],
        typing.Union[
            dict,
            schemas.immutabledict,
            str,
            datetime.date,
            datetime.datetime,
            uuid.UUID,
            int,
            float,
            bool,
            None,
            list,
            tuple,
            bytes,
            io.FileIO,
            io.BufferedReader
        ],
        bool,
    ]
]


@dataclasses.dataclass(frozen=True)
class AdditionalpropertiesAllowsASchemaWhichShouldValidate(
    schemas.DictSchema[AdditionalpropertiesAllowsASchemaWhichShouldValidateDict]
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    types: typing.FrozenSet[typing.Type] = frozenset({schemas.immutabledict})
    properties: Properties = dataclasses.field(default_factory=lambda: schemas.typed_dict_to_instance(Properties)) # type: ignore
    additional_properties: typing.Type[AdditionalProperties] = dataclasses.field(default_factory=lambda: AdditionalProperties) # type: ignore
    type_to_output_cls: typing.Mapping[
        typing.Type,
        typing.Type
    ] = dataclasses.field(
        default_factory=lambda: {
            schemas.immutabledict: AdditionalpropertiesAllowsASchemaWhichShouldValidateDict
        }
    )

    @classmethod
    def validate(
        cls,
        arg: typing.Union[
            AdditionalpropertiesAllowsASchemaWhichShouldValidateDictInput,
            AdditionalpropertiesAllowsASchemaWhichShouldValidateDict,
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> AdditionalpropertiesAllowsASchemaWhichShouldValidateDict:
        return super().validate(
            arg,
            configuration=configuration,
        )

