# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

import typing
import typing_extensions

from petstore_api import security_schemes

class ApiKey(security_schemes.ApiKeySecurityScheme):
    '''
    apiKey in header
    '''
    name = "api_key"
    in_location = security_schemes.ApiKeyInLocation.HEADER
