# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from petstore_api.shared_imports.header_imports import *

from .content.multipart_form_data import schema as multipart_form_data_schema

class RequestBody(api_client.RequestBody):


    class MultipartFormDataMediaType(api_client.MediaType):
        schema: typing_extensions.TypeAlias = multipart_form_data_schema.Schema
    Content = typing_extensions.TypedDict(
        'Content',
        {
            'multipart/form-data': typing.Type[MultipartFormDataMediaType],
        }
    )
    content: Content = {
        'multipart/form-data': MultipartFormDataMediaType,
    }
