# coding: utf-8

"""
    openapi 3.1.0 sample spec
    sample spec for testing openapi functionality, built from json schema tests for draft2020-12  # noqa: E501
    The version of the OpenAPI document: 0.0.1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

import unittest

import unit_test_api
from unit_test_api.components.schema.empty_tokens_in_ref_json_pointer import EmptyTokensInRefJsonPointer
from unit_test_api.configurations import schema_configuration


class TestEmptyTokensInRefJsonPointer(unittest.TestCase):
    """EmptyTokensInRefJsonPointer unit test stubs"""
    configuration = schema_configuration.SchemaConfiguration()

    def test_non_number_is_invalid_fails(self):
        # non-number is invalid
        with self.assertRaises((unit_test_api.ApiValueError, unit_test_api.ApiTypeError)):
            EmptyTokensInRefJsonPointer.validate(
                "a",
                configuration=self.configuration
            )

    def test_number_is_valid_passes(self):
        # number is valid
        EmptyTokensInRefJsonPointer.validate(
            1,
            configuration=self.configuration
        )


if __name__ == '__main__':
    unittest.main()
