# coding: utf-8

"""
    openapi 3.1.0 sample spec
    sample spec for testing openapi functionality, built from json schema tests for draft2020-12  # noqa: E501
    The version of the OpenAPI document: 0.0.1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

import unittest

import unit_test_api
from unit_test_api.components.schema.unevaluateditems_with_items import UnevaluateditemsWithItems
from unit_test_api.configurations import schema_configuration


class TestUnevaluateditemsWithItems(unittest.TestCase):
    """UnevaluateditemsWithItems unit test stubs"""
    configuration = schema_configuration.SchemaConfiguration(
        disabled_json_schema_keywords={'format'}
    )

    def test_invalid_under_items_fails(self):
        # invalid under items
        with self.assertRaises((unit_test_api.ApiValueError, unit_test_api.ApiTypeError)):
            UnevaluateditemsWithItems.validate(
                [
                    "foo",
                    "bar",
                    "baz",
                ],
                configuration=self.configuration
            )

    def test_valid_under_items_passes(self):
        # valid under items
        UnevaluateditemsWithItems.validate(
            [
                5,
                6,
                7,
                8,
            ],
            configuration=self.configuration
        )


if __name__ == '__main__':
    unittest.main()
