/*
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
*/

package org.openapijsonschematools.client.components.requestbodies;

import org.openapijsonschematools.client.requestbody.RequestBodySerializer;
import org.openapijsonschematools.client.mediatype.MediaType;
import org.openapijsonschematools.client.components.requestbodies.pet.content.applicationjson.Schema;
import org.openapijsonschematools.client.components.requestbodies.pet.content.applicationxml.Schema;

import java.util.AbstractMap;
import java.util.Map;

public class Pet extends RequestBodySerializer {

    public static class ApplicationjsonMediaType extends MediaType<Schema.Schema1> {
        public ApplicationjsonMediaType() {
            super(Schema.Schema1.getInstance());
        }
    }

    public static class ApplicationxmlMediaType extends MediaType<Schema.Schema1> {
        public ApplicationxmlMediaType() {
            super(Schema.Schema1.getInstance());
        }
    }

    public Pet() {
        super(
            Map.ofEntries(
                new AbstractMap.SimpleEntry<>("application/json", new ApplicationjsonMediaType()),
                new AbstractMap.SimpleEntry<>("application/xml", new ApplicationxmlMediaType())
            ),
            true
        );
    }
}
