# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from some_api.paths.config_tls_generate.post.operation import ApiForPost


class ConfigTlsGenerate(
    ApiForPost,
):
    pass
