# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from some_api.paths.system_cancel_update.post.operation import ApiForPost


class SystemCancelUpdate(
    ApiForPost,
):
    pass
