# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from some_api.paths.system_info.get.operation import ApiForGet


class SystemInfo(
    ApiForGet,
):
    pass
