# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from unit_test_api import api_client, exceptions

from unit_test_api.components.schema import additionalproperties_are_allowed_by_default

class RequestBody(api_client.RequestBody):
    content = {
        'application/json': api_client.MediaType(
            schema=additionalproperties_are_allowed_by_default.AdditionalpropertiesAreAllowedByDefault,
        ),
    }
    required = True
