package org.openapijsonschematools.client.components.schemas;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.openapijsonschematools.client.configurations.SchemaConfiguration;
import org.openapijsonschematools.client.exceptions.ValidationException;
import org.openapijsonschematools.client.schemas.validation.FrozenList;
import org.openapijsonschematools.client.schemas.validation.FrozenMap;
import org.openapijsonschematools.client.schemas.validation.ItemsValidator;
import org.openapijsonschematools.client.schemas.validation.JsonSchema;
import org.openapijsonschematools.client.schemas.validation.JsonSchemaFactory;
import org.openapijsonschematools.client.schemas.validation.KeywordEntry;
import org.openapijsonschematools.client.schemas.validation.KeywordValidator;
import org.openapijsonschematools.client.schemas.validation.TypeValidator;

public class AnimalFarm {
    // nest classes so all schemas and input/output classes can be public
    
    
    public static class AnimalFarmList extends FrozenList<Animal.AnimalMap> {
        AnimalFarmList(FrozenList<Animal.AnimalMap> m) {
            super(m);
        }
        public static AnimalFarmList of(List<Map<String, Object>> arg, SchemaConfiguration configuration) throws ValidationException {
            return JsonSchemaFactory.getInstance(AnimalFarm1.class).validate(arg, configuration);
        }
    }
    
    public class AnimalFarmListInput {
        // class to build List<Map<String, Object>>
    }
    
    
    public static class AnimalFarm1 extends JsonSchema<FrozenMap, AnimalFarmList> {
        /*
        NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
        Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
    
        Do not edit the class manually.
        */
        public AnimalFarm1() {
            super(new LinkedHashMap<>(Map.ofEntries(
                new KeywordEntry("type", new TypeValidator(Set.of(FrozenList.class))),
                new KeywordEntry("items", new ItemsValidator(Animal.Animal1.class))
            )));
        }
        
        @Override
        protected AnimalFarmList getListOutputInstance(FrozenList<?> arg) {
            return new AnimalFarmList((FrozenList<Animal.AnimalMap>) arg);
        }
        public AnimalFarmList validate(List<Map<String, Object>> arg, SchemaConfiguration configuration) throws ValidationException {
            return validateList(arg, configuration);
        }
    }}
