# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.response_body_post_invalid_string_value_for_default_response_body_for_content_types.post.operation import PostInvalidStringValueForDefaultResponseBodyForContentTypes
from unit_test_api.paths.request_body_post_invalid_string_value_for_default_request_body.post.operation import PostInvalidStringValueForDefaultRequestBody
from unit_test_api.paths.request_body_post_the_default_keyword_does_not_do_anything_if_the_property_is_missing_request_body.post.operation import PostTheDefaultKeywordDoesNotDoAnythingIfThePropertyIsMissingRequestBody
from unit_test_api.paths.response_body_post_the_default_keyword_does_not_do_anything_if_the_property_is_missing_response_body_for_content_types.post.operation import PostTheDefaultKeywordDoesNotDoAnythingIfThePropertyIsMissingResponseBodyForContentTypes


class DefaultApi(
    PostInvalidStringValueForDefaultResponseBodyForContentTypes,
    PostInvalidStringValueForDefaultRequestBody,
    PostTheDefaultKeywordDoesNotDoAnythingIfThePropertyIsMissingRequestBody,
    PostTheDefaultKeywordDoesNotDoAnythingIfThePropertyIsMissingResponseBodyForContentTypes,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
