# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.request_body_post_object_properties_validation_request_body.post.operation import PostObjectPropertiesValidationRequestBody
from unit_test_api.paths.response_body_post_object_properties_validation_response_body_for_content_types.post.operation import PostObjectPropertiesValidationResponseBodyForContentTypes
from unit_test_api.paths.request_body_post_properties_with_escaped_characters_request_body.post.operation import PostPropertiesWithEscapedCharactersRequestBody
from unit_test_api.paths.response_body_post_properties_with_escaped_characters_response_body_for_content_types.post.operation import PostPropertiesWithEscapedCharactersResponseBodyForContentTypes


class PropertiesApi(
    PostObjectPropertiesValidationRequestBody,
    PostObjectPropertiesValidationResponseBodyForContentTypes,
    PostPropertiesWithEscapedCharactersRequestBody,
    PostPropertiesWithEscapedCharactersResponseBodyForContentTypes,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
