# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.request_body_post_uniqueitems_false_validation_request_body.post.operation import PostUniqueitemsFalseValidationRequestBody
from unit_test_api.paths.request_body_post_uniqueitems_validation_request_body.post.operation import PostUniqueitemsValidationRequestBody
from unit_test_api.paths.response_body_post_uniqueitems_false_validation_response_body_for_content_types.post.operation import PostUniqueitemsFalseValidationResponseBodyForContentTypes
from unit_test_api.paths.response_body_post_uniqueitems_validation_response_body_for_content_types.post.operation import PostUniqueitemsValidationResponseBodyForContentTypes


class UniqueItemsApi(
    PostUniqueitemsFalseValidationRequestBody,
    PostUniqueitemsValidationRequestBody,
    PostUniqueitemsFalseValidationResponseBodyForContentTypes,
    PostUniqueitemsValidationResponseBodyForContentTypes,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
