# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

import decimal
import unittest

from petstore_api.components.schema import pet
from petstore_api.components.schema import category


class TesttPet(unittest.TestCase):
    """ParentPet unit test stubs"""

    def testPet(self):
        cat = category.Category({'name': 'hi', 'addprop': {'a': 1}})
        inst = pet.Pet({'photoUrls': [], 'name': 'Katsu', 'category': cat})
        self.assertEqual(
            inst,
            {
                'photoUrls': (),
                'name': 'Katsu',
                'category': {
                    'name': 'hi',
                    'addprop': {'a': decimal.Decimal('1')}
                }
            }
        )


if __name__ == '__main__':
    unittest.main()
