# coding: utf-8

"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""


import unittest

import petstore_api
from petstore_api.components.schema.nullable_string import NullableString
from petstore_api.schemas import Schema, none_type_


class TestNullableString(unittest.TestCase):
    """NullableString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNullableString(self):
        """Test NullableString"""
        inst = NullableString.validate(None)
        assert isinstance(inst, none_type_)
        assert inst is None

        inst = NullableString.validate('approved')
        assert isinstance(inst, str)
        assert inst == 'approved'

        invalid_values = (1,)
        for invalid_value in invalid_values:
            with self.assertRaisesRegex(
                petstore_api.ApiTypeError,
                r"Invalid type. Required value type is one of \[NoneType, str\] and passed type was int at \['args\[0\]'\]"
            ):
                NullableString.validate(invalid_value)


if __name__ == '__main__':
    unittest.main()
