# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from dataclasses import dataclass
import typing_extensions
import urllib3

from petstore_api import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from petstore_api import schemas  # noqa: F401




class schema(
    schemas.EnumBase,
    schemas.Int32Schema
):


    class MetaOapg:
        format = 'int32'
        enum_value_to_name = {
            1: "POSITIVE_1",
            -2: "NEGATIVE_2",
        }
    
    @schemas.classproperty
    def POSITIVE_1(cls):
        return cls(1)
    
    @schemas.classproperty
    def NEGATIVE_2(cls):
        return cls(-2)


parameter_oapg = api_client.QueryParameter(
    name="enum_query_integer",
    style=api_client.ParameterStyle.FORM,
    schema=schema,
    explode=True,
)
