# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from petstore_api.paths.fake_json_with_charset.post.operation import JsonWithCharset
from petstore_api.paths.fake_multiple_response_bodies.get.operation import MultipleResponseBodies
from petstore_api.paths.fake_multiple_securities.get.operation import MultipleSecurities
from petstore_api.paths.fake_query_param_with_json_content_type.get.operation import QueryParamWithJsonContentType
from petstore_api.paths.fake_parameter_collisions1_abab_self_ab.post.operation import ParameterCollisions
from petstore_api.paths.fake_refs_array_of_enums.post.operation import ArrayOfEnums
from petstore_api.paths.fake_additional_properties_with_array_of_enums.get.operation import AdditionalPropertiesWithArrayOfEnums
from petstore_api.paths.fake_json_patch.patch.operation import JsonPatch
from petstore_api.paths.fake_upload_files.post.operation import UploadFiles
from petstore_api.paths.fake_json_form_data.get.operation import JsonFormData
from petstore_api.paths.fake_refs_string.post.operation import String
from petstore_api.paths.fake_response_without_schema.get.operation import ResponseWithoutSchema
from petstore_api.paths.fake_refs_object_model_with_ref_props.post.operation import ObjectModelWithRefProps
from petstore_api.paths.fake_obj_in_query.get.operation import ObjectInQuery
from petstore_api.paths.fake_case_sensitive_params.put.operation import CaseSensitiveParams
from petstore_api.paths.fake_refs_arraymodel.post.operation import ArrayModel
from petstore_api.paths.fake_inline_additional_properties.post.operation import InlineAdditionalProperties
from petstore_api.paths.fake.get.operation import EnumParameters
from petstore_api.paths.fake.post.operation import EndpointParameters
from petstore_api.paths.fake.delete.operation import GroupParameters
from petstore_api.paths.fake.patch.operation import ClientModel
from petstore_api.paths.fake_inline_composition.post.operation import InlineComposition
from petstore_api.paths.fake_health.get.operation import FakeHealthGet
from petstore_api.paths.fake_refs_mammal.post.operation import Mammal
from petstore_api.paths.fake_refs_composed_one_of_number_with_validations.post.operation import ComposedOneOfDifferentTypes
from petstore_api.paths.fake_test_query_paramters.put.operation import QueryParameterCollectionFormat
from petstore_api.paths.fake_ref_obj_in_query.get.operation import RefObjectInQuery
from petstore_api.paths.fake_body_with_query_params.put.operation import BodyWithQueryParams
from petstore_api.paths.fake_refs_boolean.post.operation import Boolean
from petstore_api.paths.fake_refs_number.post.operation import NumberWithValidations
from petstore_api.paths.fake_refs_enum.post.operation import StringEnum
from petstore_api.paths.fake_delete_coffee_id.delete.operation import DeleteCoffee
from petstore_api.paths.fake_upload_file.post.operation import UploadFile
from petstore_api.paths.fake_body_with_file_schema.put.operation import BodyWithFileSchema
from petstore_api.paths.fake_upload_download_file.post.operation import UploadDownloadFile


class FakeApi(
    JsonWithCharset,
    MultipleResponseBodies,
    MultipleSecurities,
    QueryParamWithJsonContentType,
    ParameterCollisions,
    ArrayOfEnums,
    AdditionalPropertiesWithArrayOfEnums,
    JsonPatch,
    UploadFiles,
    JsonFormData,
    String,
    ResponseWithoutSchema,
    ObjectModelWithRefProps,
    ObjectInQuery,
    CaseSensitiveParams,
    ArrayModel,
    InlineAdditionalProperties,
    EnumParameters,
    EndpointParameters,
    GroupParameters,
    ClientModel,
    InlineComposition,
    FakeHealthGet,
    Mammal,
    ComposedOneOfDifferentTypes,
    QueryParameterCollectionFormat,
    RefObjectInQuery,
    BodyWithQueryParams,
    Boolean,
    NumberWithValidations,
    StringEnum,
    DeleteCoffee,
    UploadFile,
    BodyWithFileSchema,
    UploadDownloadFile,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
