# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from unit_test_api import api_client, exceptions

from unit_test_api.components.schema import allof_combined_with_anyof_oneof

parameter_oapg = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=allof_combined_with_anyof_oneof.AllofCombinedWithAnyofOneof,
        ),
    },
    required=True,
)
