# coding: utf-8

"""
    Example
    No description provided (generated by Openapi JSON Schema Generator https://github.com/openapi-json-schema-tools/openapi-json-schema-generator)  # noqa: E501
    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

import unittest

import json_schema_api
from json_schema_api.components.schema.any_type_property_names import AnyTypePropertyNames


class TestAnyTypePropertyNames(unittest.TestCase):
    """AnyTypePropertyNames unit test stubs"""

    def test_success_valid_property_names(self):
        inst = AnyTypePropertyNames.validate({'a1': 0})
        assert inst == {'a1': 0}
    
    def test_invalid_property_names_fails(self):
        with self.assertRaises(json_schema_api.ApiValueError):
            AnyTypePropertyNames.validate({'1a': 0})


if __name__ == '__main__':
    unittest.main()
