# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.request_body_post_uniqueitems_with_an_array_of_items_request_body.post.operation import ApiForPost


class RequestBodyPostUniqueitemsWithAnArrayOfItemsRequestBody(
    ApiForPost,
):
    pass
