# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.request_body_post_items_does_not_look_in_applicators_valid_case_request_body.post.operation import ApiForPost


class RequestBodyPostItemsDoesNotLookInApplicatorsValidCaseRequestBody(
    ApiForPost,
):
    pass
