# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.response_body_post_if_appears_at_the_end_when_serialized_keyword_processing_sequence_response_body_for_content_types.post.operation import ApiForPost


class ResponseBodyPostIfAppearsAtTheEndWhenSerializedKeywordProcessingSequenceResponseBodyForContentTypes(
    ApiForPost,
):
    pass
