# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.response_body_post_patternproperties_validates_properties_matching_a_regex_response_body_for_content_types.post.operation import ApiForPost


class ResponseBodyPostPatternpropertiesValidatesPropertiesMatchingARegexResponseBodyForContentTypes(
    ApiForPost,
):
    pass
