# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from unit_test_api.paths.response_body_post_if_and_else_without_then_response_body_for_content_types.post.operation import ApiForPost


class ResponseBodyPostIfAndElseWithoutThenResponseBodyForContentTypes(
    ApiForPost,
):
    pass
